name: Build & Push Backend Docker

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
      
  workflow_dispatch: {}

jobs:
  docker-build:
    name: Build and Push Docker Image to GCR
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: backend-app
      IMAGE_TAG: latest
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}       # ID project GCP
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}       # Service Account JSON

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      # 4. Configure Docker for GCR
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      # 5. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG} ./backend

      # 6. Push Docker image to GCR
      - name: Push Docker Image to GCR
        run: |
          docker push gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:${IMAGE_TAG}
